from fastapi import APIRouter
from pydantic import BaseModel, Field

router = APIRouter(prefix="/outreach", tags=["outreach"])


class OutreachDraftRequest(BaseModel):
    job_id: str | None = None
    recipient_email: str = Field(..., min_length=3)
    extra_context: str | None = None


class OutreachDraft(BaseModel):
    subject: str
    body: str
    recipient_email: str = Field(..., min_length=3)


@router.post("/draft", response_model=OutreachDraft)
def draft_outreach(payload: OutreachDraftRequest) -> OutreachDraft:
    return OutreachDraft(
        subject="Exploring a fit on your team",
        body="Draft will be generated by the ai-service Outreach Draft Agent.",
        recipient_email=payload.recipient_email,
    )


@router.post("/send")
def send_outreach(payload: OutreachDraft) -> dict[str, str]:
    return {"status": "queued", "provider": "gmail", "recipient": payload.recipient_email}
